version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: api_notas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: upacifico